### ISSUE TITLE
Criação de Arquivo de Contribuição

### ISSUE THREAD

**Issue by stephan-lopes** [Abacatinhos/agenda-tech-brasil#205]
# Descrição

Criar um arquivo de contribuição que explique passo-a-passo como contribuir com o repositório. Esse arquivo pode ser o padrão do GH (CONTRIBUTING.md), onde deve conter as seguintes informações:

- Tipos de Contribuição
  - Abrir Issues com Informações Eventos
  - Editar Eventos com Datas Erradas/Atualizadas
  - Adicionar o Evento no README.md
- Passo-a-Passo
  - Adicionando Eventos com Issue
  - Adicionando Eventos no README.md
    - Padrão de Escrita dos Eventos Online
    - Padrão de Escrita dos Eventos Híbridos e Presenciais

# Objetivo

O objetivo dessa modificação, é deixar mais informativo para quem chega no repositório, como pode contribuir e ajudar ele a continuar ativo e com eventos atualizados.

# Tarefas

- [ ] Criar arquivo de contribuição.
- [ ] Adicionar as informações de contribuição.
- [ ] Adicionar link para o arquivo de contribuição nas informações da seção do README.md que informa como contribuir.

**Comment by actiago** [comment]
Olá, @stephan-lopes 

Uma recomendação para um CONTRIBUTING.md bem que pode ser ajustado de acordo com o objetivo proposto é este aqui (https://github.com/badtuxx/DescomplicandoDocker/blob/main/CONTRIBUTING.md).

**Comment by stephan-lopes** [comment]
Resolvido no PR #328
