### ISSUE TITLE
Idea - Search Engine 

### ISSUE THREAD

**Issue by CllsPy** [Abacatinhos/agenda-tech-brasil#421]
Oi, ótimo trabalho e disciplina em manter o repositório funcionando!

Quando descobri a plataforma há algumas semanas, pensei em usar NLP e Scraping para criar um filtro. Ainda tenho planos para isso, ansioso 
que sou construi um MVP com Genai.

**Enviei um e-mail para um dos organizadores, mas não recebi resposta.**

[Aqui](https://github.com/CllsPy/AvoSearch-) está uma pequena demo da ideia, em vídeo. Não fiz o deployment porque ainda preciso fazer testes mais robustos.

Quem sabe esta ideia não possa tomar forma e se tornar algo definitivo, espero de  inspirar algo em escala e que possa impulsionar ainda mais o projeto de vocês, (:

Atenciosamente,  
cll

**Comment by stephan-lopes** [comment]
@pachicodes

**Comment by stephan-lopes** [comment]
Oi @CllsPy, tudo bem? Perdão não ter dado uma resposta antes, estava muito corrido por aqui. 

**O intuito do repositório seria ter uma base centralizada de agendas/eventos que acontecem no Brasil.** 

Não há problema algum em você desenvolver a ferramenta que está desenvolvendo, utilizando esse repositório como fonte desses dados. Apenas não queremos adicionar mais complexidades aqui, como por exemplo, em criar aplicações que utilizem ele como fonte. 

Você pode criar algo externo a ele, sem problemas, apenas não temos o desejo de adicionar soluções que fogem dessa visão no momento dentro dele.

Para sua aplicação, caso eu possa sugerir algo sobre ela, sugiro alterar para ao invés de usar o Markdown, utilizar o arquivo de json que agora temos disponível. Talvez por lá, consiga manipular melhor os dados.

Qualquer contribuição para melhorar os códigos existentes aqui, adicionar eventos, remover eventos ou facilitar a manipulação da criação, edição ou exclusão de eventos, será super bem-vinda! 

Agradeço a proatividade, e gostaria, se possível, de ter sua contribuição em alguma dessas formas que falei anteriormente, no futuro. 😁

**Comment by CllsPy** [comment]
@stephan-lopes!

Fico muito feliz em saber sobre o posicionamento de vocês em relação à complexidade. Essa é uma postura que também adoto nos meus projetos. Inicialmente, **eu não estava considerando a possibilidade de integração**, mas gostaria muito de ouvir a opinião de vocês e obter algum feedback.

**A propósito, obrigado! Vou utilizar o JSON, sim.**

Mais uma vez, parabéns pelo trabalho incrível! **Vocês certamente conquistaram mais uma pessoa que admira profundamente** o que foi feito nesta plataforma tão distinta.
